Fixes #371
LIlGG/halo-theme-sakura pull request #376
Opened 2023-07-17 16:04 UTC by LostAttractor

Fixes #371

发现箭头不居中为`font-size: 1.75rem;`属性所致，去除即恢复正常
所以给了个`left: -0.875rem`解决

![image](https://github.com/LIlGG/halo-theme-sakura/assets/46527539/5c463471-19af-47e2-baf4-6a32b2f91178)

不过虽然箭头是这样对齐了，但是这个div还是没对齐，鄙人不是做前端的不是很懂CSS，不过推测是因为居中的实现方法是`left:50%`，但我也不知道应该怎么居中好（
![image](https://github.com/LIlGG/halo-theme-sakura/assets/46527539/c42fe851-ff82-4bdf-a6d2-ce1e94ac7e4a)

居中问题的话，通过在`lower-container`的css增加`position: absolute;`解决了，halo1的版本中是有这个修饰的

此外，我没有npm run build，我构建会失败
```
[vite]: Rollup failed to resolve import "APlayer" from "/home/lostattractor/Documents/GitHub/halo-theme-sakura/src/module/utils.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "APlayer" from "/home/lostattractor/Documents/GitHub/halo-theme-sakura/src/module/utils.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/lostattractor/Documents/GitHub/halo-theme-sakura/node_modules/vite/dist/node/chunks/dep-abb4f102.js:48051:27)
    at onRollupWarning (file:///home/lostattractor/Documents/GitHub/halo-theme-sakura/node_modules/vite/dist/node/chunks/dep-abb4f102.js:48083:9)
    at onwarn (file:///home/lostattractor/Documents/GitHub/halo-theme-sakura/node_modules/vite/dist/node/chunks/dep-abb4f102.js:47814:13)
    at file:///home/lostattractor/Documents/GitHub/halo-theme-sakura/node_modules/rollup/dist/es/shared/node-entry.js:24070:13
    at Object.logger [as onLog] (file:///home/lostattractor/Documents/GitHub/halo-theme-sakura/node_modules/rollup/dist/es/shared/node-entry.js:25742:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/lostattractor/Documents/GitHub/halo-theme-sakura/node_modules/rollup/dist/es/shared/node-entry.js:24656:26)
    at ModuleLoader.resolveDynamicImport (file:///home/lostattractor/Documents/GitHub/halo-theme-sakura/node_modules/rollup/dist/es/shared/node-entry.js:24714:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/lostattractor/Documents/GitHub/halo-theme-sakura/node_modules/rollup/dist/es/shared/node-entry.js:24601:32
```
根据提示在build.rollupOptions.external增加`APlayer`和`APlayer/dist/APlayer.min.css?used`后可以构建了但是构建出来的`/assets/dist/`就会没有aplayer的js和css，不知道正确应该是怎么构建的，请教一下，到时候我补上
此外，构建也可以加个ci（

2023-07-17 16:08 UTC, LIlGG commented
是否使用了 `pnpm install` 进行依赖包下载？后续会增加 ci 进行构建

2023-07-17 16:09 UTC, LIlGG commented
目前也缺少关于开发的文档，找机会我会补充一下。

2023-07-18 07:34 UTC, LostAttractor commented
> 是否使用了 `pnpm install` 进行依赖包下载？后续会增加 ci 进行构建

是的，npm和pnpm我都试了，都不行
不确定和我在用NixOS有没有什么关系，Nix的环境比较怪

2023-07-18 14:31 UTC, LIlGG requested changes

2023-07-18 14:31 UTC, LIlGG commented on src/css/common/outline/header/menu.css
>    text-align: center;
```suggestion
  text-align: center;
```
这里无需修改

2023-07-20 13:29 UTC, LostAttractor commented on src/css/common/outline/header/menu.css
>    text-align: center;
> 这里无需修改

这不不使用`position: absolute;`的话，如果不设置站点头像（使用标题作为左上角），菜单便会不居中，设置了会正常

2023-07-20 13:43 UTC, LIlGG approved these changes

2023-07-20 13:45 UTC, LIlGG commented
非常完美，它能够正常工作并且符合预期，感谢提供的 PR。

2023-07-20 13:46 UTC, merged