feat: customize resource identifier param name
LIlGG/halo-theme-sakura pull request #530
Opened 2024-06-12 05:08 UTC by ShiinaKin

![image](https://github.com/LIlGG/halo-theme-sakura/assets/52254895/034f4e72-adde-4c1b-adb0-367757967aca)
![image](https://github.com/LIlGG/halo-theme-sakura/assets/52254895/2c167e36-b12f-48a1-846e-cfd8850d6557)
![image](https://github.com/LIlGG/halo-theme-sakura/assets/52254895/503986cb-4504-4796-aa84-cfff92f8c47a)

#522

2024-06-12 06:50 UTC, LIlGG requested changes
Hi，感谢提供此 PR。不过配置项可能需要进行一定的修改

2024-06-12 06:50 UTC, LIlGG commented on settings.yaml
> +          help: 随机图 API 资源标识变量，默认为postid，可根据随机图 API 的需要自行设置。
建议仅在选择文章支持使用随机图后再展示此项。

```suggestion
        - $formkit: text
        	if: "$get(rimage_cover_open).value == true"
          name: rimage_custom_param_name
          label: 随机图 API 资源标识变量
          validation: "required"
          value: postid
          help: 随机图 API 资源标识变量，默认为 postid，可根据随机图 API 的需要自行设置。
```

2024-06-12 06:53 UTC, ShiinaKin commented
By the way，希望在此pr合并后发个小版本，😀

2024-06-12 06:54 UTC, LIlGG commented on settings.yaml
> +          help: 随机图 API 资源标识变量，默认为postid，可根据随机图 API 的需要自行设置。
位置也可能需要调整一下，建议放在 `rimage_cover_open` 即文章使用随机封面图下面，防止用户选择之后再其上突然出现一个输入框造成误解。

2024-06-12 06:56 UTC, LIlGG commented
> By the way，希望在此pr合并后发个小版本，😀

可以考虑发布一个小版本。

2024-06-12 08:01 UTC, LIlGG commented
它工作的很好，非常感谢提交此 PR。

2024-06-12 08:01 UTC, merged

2024-06-13 05:46 UTC, ruibaby commented
@all-contributors please add @ShiinaKin  for code