fix: the issue of the menu icon not being vertical  center
LIlGG/halo-theme-sakura pull request #569
Opened 2024-08-23 08:55 UTC by LIlGG

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

解决导航栏图标未能垂直居中的问题

#### How to test it?

测试菜单图标是否垂直居中。
测试其他所有图标是否垂直居中。
测试是否会对界面其他元素有影响。

#### Which issue(s) this PR fixes:

Fixes #554 

#### Does this PR introduce a user-facing change?
```release-note
解决导航栏图标未能垂直居中的问题
```

2024-08-23 08:59 UTC, LIlGG commented
hi, @ShiinaKin ，我将 `.iconify` 中的 top 取消了，并对所有使用 icon 的位置使用了 flex 的居中方式。有空时你可以验证一下是否符合需求。

另外，由于改变了父元素的 `display`，因此有可能会导致某些内容受到影响。

2024-08-23 09:32 UTC, ShiinaKin commented
![image](https://github.com/user-attachments/assets/a1c34f7f-dae3-4ca5-b7db-d138539c8830)

seems good, 符合预期

2024-08-25 12:25 UTC, ruibaby requested changes

2024-08-25 12:25 UTC, ruibaby commented on src/css/common/architecture/base.css
> +.items-center {
建议改个名字，这个名字直观上看起来仅针对 `align-items: center`，但里面包含了 display 和 gap。

2024-09-05 09:12 UTC, ruibaby approved these changes

2024-09-13 06:24 UTC, ShiinaKin commented
@LIlGG 请问这个pr还有什么问题吗，不能发正式版的话，希望先发一个rc

2024-09-14 13:44 UTC, LIlGG commented
> @LIlGG 请问这个pr还有什么问题吗，不能发正式版的话，希望先发一个rc

最近在忙于其他项目，所以没有对主题进行维护，待此 PR 合并后再修改一些其他问题后会发正式版本。

2024-09-14 13:52 UTC, ruibaby commented
> > @LIlGG 请问这个pr还有什么问题吗，不能发正式版的话，希望先发一个rc
> 
> 
> 
> 最近在忙于其他项目，所以没有对主题进行维护，待此 PR 合并后再修改一些其他问题后会发正式版本。

什么项目

2024-10-04 11:59 UTC, merged