从jsdelivr获取静态资源
LIlGG/halo-theme-sakura pull request #58
Opened 2020-08-24 06:58 UTC by blessingCN

涉及替换的资源有：
1. 第一屏上的社交图标
2. `highlight.css` `highlight.js` `highlight-line-num`
3. `jqcloud`

部分静态资源的版本有变动，但功能不受影响（目前仅在[我的网站](https://meow.mashiro.best)上测试过）

2020-08-24 11:46 UTC, LIlGG commented
不是很建议使用开发版资源。。
比如app.min.js，因为这样做的话，用户使用的app.min.js永远都会是最新的，将会导致例如1.0.0的用户使用了我正在开发的1.2.0的资源。而且不会走用户自己的cdn。
所以建议不要链接资源到本仓库，尤其是master。因为本仓库结构一旦发生变化，将会出现用户资源丢失的问题。
建议可以向我的cdn仓库提交pr，然后使用固定的版本号。

2020-08-24 12:10 UTC, blessingCN commented
能找到官方提供cdn的资源我都会尽量使用官方的cdn（比如highlight）

像不怎么变动的静态文件（如第一屏的图标）这样的资源，您觉得是 走cdn仓库好 还是 直接使用项目内的好呢？

需要撤销cdn的文件我目前认为有：style.min.css 和 app.min.js ，您认为还有那些需要撤回的文件呢？

2020-08-24 12:14 UTC, LIlGG commented
> 能找到官方提供cdn的资源我都会尽量使用官方的cdn（比如highlight）
> 
> 像不怎么变动的静态文件（如第一屏的图标）这样的资源，您觉得是 走cdn仓库好 还是 直接使用项目内的好呢？
> 
> 需要撤销cdn的文件我目前认为有：style.min.css 和 app.min.js ，您认为还有那些需要撤回的文件呢？

不要使用master作为静态资源的地址，因为不确定是否将来的某一天会变动这个地址或者文件内容。
对于静态资源来说，使用固定版本的版本是最好的做法

2020-08-24 12:24 UTC, LIlGG commented
> 能找到官方提供cdn的资源我都会尽量使用官方的cdn（比如highlight）
> 
> 像不怎么变动的静态文件（如第一屏的图标）这样的资源，您觉得是 走cdn仓库好 还是 直接使用项目内的好呢？
> 
> 需要撤销cdn的文件我目前认为有：style.min.css 和 app.min.js ，您认为还有那些需要撤回的文件呢？

> 能找到官方提供cdn的资源我都会尽量使用官方的cdn（比如highlight）
> 
> 像不怎么变动的静态文件（如第一屏的图标）这样的资源，您觉得是 走cdn仓库好 还是 直接使用项目内的好呢？
> 
> 需要撤销cdn的文件我目前认为有：style.min.css 和 app.min.js ，您认为还有那些需要撤回的文件呢？

另外对于highlight的代码，包括其css，实际上与style.css 和 app.js 道理相同，他们都属于开发阶段可能会大量改变的地方，且用户可能自定义的地方。
highlight应该由用户自己可以添加自己想要的语言高亮（默认只会提供一部分），而不是规定死的。
之前是想过全部使用jsdelivr的，但考虑到一些问题，也就搁置了

2020-08-24 12:28 UTC, blessingCN commented
highlight后续会考虑通过在主题设置中追加配置来达到自定义效果吗？

2020-08-24 12:33 UTC, LIlGG commented
> highlight后续会考虑通过在主题设置中追加配置来达到自定义效果吗？

这个还是比较困难的，毕竟语言的种类太多了，主题最多只能加一个填写highlight的外链。但如果用户填写的不正确 又会导致代码高亮报错，并且也不是所有用户都有外链。所以目前就是将highlight放在项目目录下，如果某个用户有需求，可以自己去官网下载然后覆盖默认的

2020-08-24 12:43 UTC, blessingCN commented
我去除了所有使用@master的资源，剩余保留的是带有固定版本号的cdn资源。

2020-08-24 12:43 UTC, LIlGG commented
嗯 今天先不合并了，明天我在你的pr上面再进行一些改动，然后再合并。非常感谢你的提交！！！

2020-08-24 12:47 UTC, LIlGG commented
> 我去除了所有使用@master的资源，剩余保留的是带有固定版本号的cdn资源。

对了，不知道你有没有时间一起来完善这个主题，讲道理一个人确实比较难。如果你愿意或者有时间的话，我想邀请你成为协作者

2020-08-24 12:52 UTC, blessingCN commented
其实之前我有参与一点点原主题的维护工作（真的就一点点），能力有限，但我愿尽一份力。

2020-08-24 12:54 UTC, LIlGG commented
> 其实之前我有参与一点点原主题的维护工作（真的就一点点），能力有限，但我愿尽一份力。

哈哈。有参与过原主题那就太好了，也会对这个熟悉的很多。非常感谢！！

2020-08-25 04:16 UTC, ruibaby commented
啊啊啊啊啊，我也想参与。

2020-08-25 04:19 UTC, ruibaby requested changes

2020-08-25 04:19 UTC, ruibaby commented on header.ftl
> +	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/darcula.min.css">
```diff
- <link href="${theme_base!}/plugins/highlight/css/highlight-${settings.code_pretty!'Default'}.css" type="text/css" rel="stylesheet" />
+ <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/darcula.min.css">
```

这里的 `darcula` 应该是在主题设置里配置的。 `${settings.code_pretty!'Default'}`，而且两者的命名可能会不一样。可能还需要改 settings.yaml 里面管理代码高亮的配置。

2020-08-25 04:26 UTC, LIlGG commented on header.ftl
> +	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/darcula.min.css">
嗯 对 这个地方是需要与 settings.yaml 相对应的 而且对于不同的代码高亮风格，用户可能会有不同的设置，而且不太方便在公共style里面加。 所以这个地方最好是使用本地的

2020-08-25 04:28 UTC, ruibaby commented on header.ftl
> +	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/darcula.min.css">
> 嗯 对 这个地方是需要与 settings.yaml 相对应的 而且对于不同的代码高亮风格，用户可能会有不同的设置，而且不太方便在公共style里面加。 所以这个地方最好是使用本地的

放在cdn没什么问题啊，只要和他们的样式列表对应就行了。

2020-08-25 04:34 UTC, blessingCN commented on header.ftl
> +	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/darcula.min.css">
目前先回调了

2020-08-25 04:37 UTC, LIlGG commented on header.ftl
> +	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/darcula.min.css">
> > 嗯 对 这个地方是需要与 settings.yaml 相对应的 而且对于不同的代码高亮风格，用户可能会有不同的设置，而且不太方便在公共style里面加。 所以这个地方最好是使用本地的
> 
> 放在cdn没什么问题啊，只要和他们的样式列表对应就行了。

但你想想 有的代码高亮可能是黑底白字 有的是白底黑字， 你样式列表对应了 用户如果改变了代码高亮的设置，那么也得继续改公共css来修正。
另外就是这个东西和style.css一样 都属于我开发阶段可能会一直改的东西 如果放在cdn上很不利于开发

2020-08-25 04:39 UTC, ruibaby commented on header.ftl
> +	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/darcula.min.css">
> > > 嗯 对 这个地方是需要与 settings.yaml 相对应的 而且对于不同的代码高亮风格，用户可能会有不同的设置，而且不太方便在公共style里面加。 所以这个地方最好是使用本地的
> 
> > 
> 
> > 放在cdn没什么问题啊，只要和他们的样式列表对应就行了。
> 
> 
> 
> 但你想想 有的代码高亮可能是黑底白字 有的是白底黑字， 你样式列表对应了 用户如果改变了代码高亮的设置，那么也得继续改公共css来修正。
> 
> 另外就是这个东西和style.css一样 都属于我开发阶段可能会一直改的东西 如果放在cdn上很不利于开发

好像是哦，你对样式定制过的。

2020-08-25 04:44 UTC, blessingCN commented on header.ftl
> +	<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/darcula.min.css">
我在想其实可以做一个release分支，在这个分支里可以把这些资源替换成cdn上的。

2020-08-25 05:46 UTC, LIlGG commented on header.ftl
> +	<<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jqcloud2@2.0.3/dist/jqcloud.min.css">
```suggestion
	<<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jqcloud2@2.0.3/dist/jqcloud.min.css">
```

2020-08-25 05:54 UTC, LIlGG commented
先合并这次提交的吧

2020-08-25 05:54 UTC, merged